spring:
  application:
    name: config-service
  profiles:
    active: local
  cloud:
    config:
      server:
        git:
          uri: https://github.com/stealhead/config-repo.git
          searchPaths:
            - '/conf'
          username: 418364620@qq.com
          password: 6620337yue
server:
  port: 8888